<?php

/**
 * @file
 * Implements hook_theme().
 */

/**
 * {@inheritdoc}
 */
function time_zone_theme() {
  $theme['time-zone-block'] = [
    'variables' => [
      'country' => NULL,
      'city' => NULL,
      'date' => NULL,
    ],
    'template' => 'block--timezoneblock',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function time_zone_preprocess_block(&$variables) {
  // Attach custom CSS library to the block template.
  $variables['#attached']['library'][] = 'time_zone/time_zone_style';
  $variables['#attached']['library'][] = 'time_zone/time-zone-update';
}
